### ISSUE TITLE
Calculation error affects some % of test cases

### ISSUE THREAD

**Issue by jdewar** [mwmiller/ed25519_ex#4]
Using the default hash function, testing the file at https://ed25519.cr.yp.to/software.html I came across some errors.

I can post more, but the first one that stopped things was a 'point not on the curve', line 68 in the sign.input file at the url

privatekey:  bcbcf561ecc05a41c7d7e55e696d32ce39b4d03c1f5f3f3a8927fe5e62e844b2
publickey:  4ddf53fad6a7a9ed30f3afecca136fd7843b72c243090891ae4021a32cadff1a
message:  6f6716b6784740980aebc3248807e31c1286ac7b681c00b66c88ff7a336d441fa5c3eb256d20cf6d1ac92ccfe4be6dcc41b1aff846d360c243001cabdfbf1a9b240455
signature:  9ff15115f6661f3211d7a40764967629ba6a5263951bdc3c6a4c90d070f7be00024b80d83b6bc27587fcff5f5ccc0eb3cde1497cf56895147a063f61f08adf0b

**Comment by jdewar** [comment]
I just by chance read the help for :binary.encode_unsigned

"Converts a positive integer to the smallest possible representation in a binary digit representation, either big endian or little endian."

Maybe the 'smallest possible' is causing the issue; I noticed the 'rightsize' function that tacks on bytes bc it was noticed that sometimes there was a size issue w/ the signature.

**Comment by mwmiller** [comment]
I've reworked the cr.yp.to example file to be a direct import of the `sign.input` file.  I am able to reproduce a failure.  I'm looking into suspected padding issues.

Thanks so much for the report.
